# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Deep Learning Review'
description: "Postings about what i learned and what i have to learn, especially about Deep Learning"

# Author's info
author: 'joongkyunKim'
# edit 'categories' in the front matter of every post to match this username
nickname: joongkyunKim
bio: 'Undergraduated student@Seoul National University'
location: 'Seoul, Korea'
url: 'http://joongkyunKim.github.io'
image: 'assets/images/myphoto.png'

short_url: 'joongkyunKim.github.io'
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
#permalink: /author/:username
#permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: joongkyunKim
repo: joongkyunKim.github.io
branch: master
#destination: ../blog-pages/
production_url:  https://joongkyunKim.github.io
source_url:      https://github.com/joongkyunKim

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
